INSERT INTO `kb-daas-dev.mart_200723.category_daily_top_100` (
  TYPE, CHANNEL, CATEGORY, WRITE_DAY, CNT, CNT_DOC, RANK, ROW_NUM
)
SELECT
  TYPE, CHANNEL, CATEGORY, WRITE_DAY, CNT, CNT_DOC, RANK, ROW_NUM
FROM (
  SELECT
    RANK() OVER (PARTITION BY WRITE_DAY, TYPE, CHANNEL ORDER BY CNT DESC) AS rank
    , ROW_NUMBER() OVER (PARTITION BY WRITE_DAY, TYPE, CHANNEL ORDER BY CNT DESC) AS row_num
    , WRITE_DAY
    , CHANNEL
    , TYPE
    , CATEGORY
    , CNT
    , CNT_DOC
  FROM (
    SELECT
      WRITE_DAY
      , CHANNEL
      , TYPE
      , CATEGORY
      , SUM(CNT) AS CNT
      , SUM(CNT_DOC) AS CNT_DOC
    FROM
      `kb-daas-dev.mart_200723.category`
    WHERE
      WRITE_DAY BETWEEN 20200601 AND 20200630
    GROUP BY
      WRITE_DAY
      , CHANNEL
      , TYPE
      , CATEGORY
  )
)
WHERE
  ROW_NUM <= 100
