# for bank keyword
INSERT INTO `kb-daas-dev.mart_200723.sentence` (
  TYPE, ID, CHANNEL, S_NAME, SB_NAME, WRITE_DAY, CATEGORY, SENTENCE1, SENTENCE2, SENTENCE3
) 
SELECT
  1 AS type
  , A.ID AS ID
  , A.CHANNEL AS CHANNEL
  , A.S_NAME AS S_NAME
  , A.SB_NAME AS SB_NAME
  , CAST(FORMAT_DATE('%Y%m%d', DATE(A.WRITESTAMP, 'Asia/Seoul')) as INT64) as day
  , (CASE 
      WHEN ARRAY_LENGTH(D2C) > 0 THEN D2C[SAFE_OFFSET(0)].label
      ELSE NULL
    END) AS CATEGORY
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 0 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(0)].idx)]
      ELSE NULL
    END) AS SENTENCE1
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 1 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(1)].idx)]
      ELSE NULL
    END) AS SENTENCE2
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 2 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(2)].idx)]
      ELSE NULL
    END) AS SENTENCE3
FROM
  `kb-daas-dev.master_200723.keyword_bank_result` A
WHERE
  A.CRAWLSTAMP > TIMESTAMP('2020-06-01 00:00:00', 'Asia/Seoul')
  --AND A.CRAWLSTAMP < TIMESTAMP('2020-06-02 00:00:00', 'Asia/Seoul')
  AND DATE(A.WRITESTAMP, 'Asia/Seoul') BETWEEN '2020-05-31' AND '2020-06-30'
  AND A.RESPONSE.status_code = 200;


# for corona keyword
INSERT INTO `kb-daas-dev.mart_200723.sentence` (
  TYPE, ID, CHANNEL, S_NAME, SB_NAME, WRITE_DAY, CATEGORY, SENTENCE1, SENTENCE2, SENTENCE3
) 
SELECT
  2 AS type
  , A.ID AS ID
  , A.CHANNEL AS CHANNEL
  , A.S_NAME AS S_NAME
  , A.SB_NAME AS SB_NAME
  , CAST(FORMAT_DATE('%Y%m%d', DATE(A.WRITESTAMP, 'Asia/Seoul')) as INT64) as day
  , (CASE 
      WHEN ARRAY_LENGTH(D2C) > 0 THEN D2C[SAFE_OFFSET(0)].label
      ELSE NULL
    END) AS CATEGORY
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 0 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(0)].idx)]
      ELSE NULL
    END) AS SENTENCE1
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 1 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(1)].idx)]
      ELSE NULL
    END) AS SENTENCE2
  , (CASE
      WHEN ARRAY_LENGTH(KSE) > 2 THEN SS[SAFE_OFFSET(KSE[SAFE_OFFSET(2)].idx)]
      ELSE NULL
    END) AS SENTENCE3
FROM
  `kb-daas-dev.master_200723.keyword_corona_result` A
WHERE
  A.CRAWLSTAMP > TIMESTAMP('2020-06-01 00:00:00', 'Asia/Seoul')
  --AND A.CRAWLSTAMP < TIMESTAMP('2020-06-02 00:00:00', 'Asia/Seoul')
  AND DATE(A.WRITESTAMP, 'Asia/Seoul') BETWEEN '2020-05-31' AND '2020-06-30'
  AND A.RESPONSE.status_code = 200;
